apiVersion: v1
kind: Service
metadata:
  name: microservices-api-gateway-service
spec:
  selector:
    app: microservices-api-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
